name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          npm i
          npm run build
          git config --global user.email "gilzon.me@gmail.com"
          git config --global user.name "Gilson Gilbert"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}